---
title: "About This Website"
---

Hello! My name is Douglas Post, I am currently a student at Georgetown University in the M.S. Data Science and Analytics program. I am graduating this December (2020), and am very excited to start my career in the data/analytics/machine learning fields. I am very passionate about data and its huge range of applications seen in the past decade. 

I am currently a Data Visualization and Analytics intern at QED Group LLC., where I have had the pleasure of working on programs that are working very hard to spread data literacy around the world. QED Group, as an international development organization focused on Monitoring and Evaluation, was a great place to start and help push a lot of these initiatives. I will hold this position from May 2020 to December 2020. 

I am also in the Massive Data Institute at Georgetown's Scholars Program. I have been in this program since January of 2020, and the research I have been able to be a part of in the program is some of my favorite I have been able to do so far in my life. I was lucky enough to be able to join a project aiming to improve the predictive techniques for large forced movements around the world. A lot more information on the project and my work is available in the "Research Projects" tab of the main navigation menu above.
